language: node_js
node_js:
  - "5.8.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install useragent
  - npm install karma-phantomjs-launcher
  - npm install angular-ui-router
  - npm install angular-mocks

